FROM python:3.9
# Gets the 3.9 version of python for docker image

# to get the logs and see whats happening
ENV PYTHONUNBUFFERED 1

# CREATE THE WORKING DIRECTORY WITHIN THE CONTAINER
WORKDIR /app


