version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    # means the files in current directory are associated with the container
    volumes:
      - .:/app